doves_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from members.views import index_view, instant_cover_view, isucc_view, view_request_view, logout_view, payment_view, transaction_check_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("members/", include('members.urls')),
    path("", index_view, name="index"),
    path("get-instant-cover/", instant_cover_view, name="instant"),
    path("success-instant-cover/", isucc_view, name="succ"),
    path("view-request/<int:pk>/", view_request_view, name="view_request"),
    path("pay-for-request/<int:pk>/", payment_view, name="pay_request"),
    path("check_paynow_transaction_status/<int:pk>/",
         transaction_check_view, name="check_paynow_transaction_status"),

    path("logout/", logout_view, name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

members/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import (
    register_view, login_view, profile_view, add_dependant_view, view_dependant_view,
    dependants_view, edit_dependant_view, delete_dependant_view, claims_view, claim_cover_view,
    cash_request_view, cashbacks_view, delete_cash_back_view, heath_assessment_view
)

app_name = "members"

dependant_patterns = [
    path('', dependants_view, name="dependants"),
    path("<int:pk>/", view_dependant_view, name="view_dependant"),
    path("<int:pk>/edit/", edit_dependant_view, name="edit_dependant"),
    path("<int:pk>/delete/", delete_dependant_view, name="delete_dependant"),
    path('add/', add_dependant_view, name="add_dependant"),
]

cash_patterns = [
    path('', cashbacks_view, name="cashbacks"),
    path('request/', cash_request_view, name="cashback_request"),
    path('<int:pk>/delete/', delete_cash_back_view, name="delete_cashback"),
]


claim_patterns = [
    path('', claims_view, name="claims"),
    path('<int:dependant>/add/', claim_cover_view, name="claim"),
]

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path('profile/', profile_view, name='profile'),
    path('health-assessment/', heath_assessment_view, name='health_assessment'),
    path('dependants/', include(dependant_patterns)),
    path('claims/', include(claim_patterns)),
    path('cashback/', include(cash_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

members/models.py
from datetime import datetime, date
import re

from django.db import models
from django.core.validators import ValidationError, RegexValidator
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils.timesince import timesince
from django.urls import reverse

from model_utils.models import TimeStampedModel

from policies.models import Policy


class Member(TimeStampedModel):

    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    MARRIED = 'M'
    SINGLE = 'S'
    DIVORCED = 'D'
    WIDOWED = 'W'
    MARITAL_STATUSES = (
        (MARRIED, "Married"),
        (SINGLE, 'Single'),
        (DIVORCED, 'Divorced'),
        (WIDOWED, 'Widowed'),
    )

    user_account = models.OneToOneField(
        settings.AUTH_USER_MODEL, null=True, blank=True, verbose_name=_("User account"),
        on_delete=models.SET_NULL, editable=False,
        related_name="record", help_text=_("User account.")
    )
    first_name = models.CharField(
        verbose_name=_("First name"), max_length=255,
        help_text=_("Member's first name(s)."),
    )
    last_name = models.CharField(
        verbose_name=_("Last name"), max_length=255,
        help_text=_("Member's last name.")
    )
    email_address = models.EmailField(
        verbose_name=_("Email address"), unique=True, help_text=_("Member email address"),
    )
    national_id = models.CharField(
        verbose_name=_("National ID"), max_length=12,
        help_text=_("National ID number."),
        validators=[
            RegexValidator(
                regex=r'\d{2}\d{6,7}[a-zA-Z]{1}\d{2}',
                message='ID Number should match format like: 58 398766 B 25, without the spaces.',
            )
        ]
    )
    date_of_birth = models.DateField(
        verbose_name=_("Date of birth"),
        help_text=_("Member's date of birth.")
    )
    sex = models.CharField(
        verbose_name=_("Sex"), max_length=1,
        choices=SEX_CHOICES,
        help_text=_("Member's sex orientation.")
    )
    date_joined = models.DateField(
        verbose_name=_("Date joined"),
        help_text=_("Date when member signed up for policy.")
    )
    policy = models.ForeignKey(
        Policy, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Policy"),
        related_name="members", help_text=_("Policy signed up for.")
    )
    marital_status = models.CharField(
        verbose_name=_("Marital status"), max_length=1,
        choices=MARITAL_STATUSES, default=MARRIED, help_text=_("Member's marital status.")
    )

    class Meta:
        verbose_name_plural = _("Members")

    def __str__(self):
        return f"{self.full_name}, {self.sex}".title()

    @property
    def full_name(self):
        return f"{self.last_name} {self.first_name}".title()
    full_name.fget.short_description = _("Full name(s)")

    @property
    def marital_status_display(self):
        return self.get_marital_status_display()
    marital_status_display.fget.short_description = _("Marital Status")

    @property
    def age(self):
        today = date.today()
        age = today.year - self.date_of_birth.year - \
            ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return age
    age.fget.short_description = _("Age")

    @property
    def dependant_count(self):
        return self.dependants.count()
    dependant_count.fget.short_description = _("Dependants")

    @property
    def dependant_count_percentage(self):
        return (self.dependant_count/self.policy.dependants_per_holder) * 100

    @property
    def claim_count(self):
        return Claim.objects.filter(dependant__member=self).count()
    claim_count.fget.short_description = _("Claims made")

    @property
    def claims(self):
        return Claim.objects.filter(dependant__member=self)

    @property
    def last_claim_date(self):
        try:
            return Claim.objects.filter(dependant__member=self).order_by('-date_of_claim')[0]
        except:
            return None
    last_claim_date.fget.short_description = _("Last claim")

    @property
    def days_since_last_claim(self):
        if self.last_claim_date is None:
            return (datetime.now().date() - self.date_joined).days
        else:
            return (datetime.now().date() - self.last_claim_date.date_of_claim).days

    @property
    def days_since_last_cashback(self):
        if self.last_cashback_date is not None:
            return (datetime.now().date() - self.last_cashback_date.created.date()).days
        else:
            return (datetime.now().date() - self.date_joined).days

    @property
    def last_cashback_date(self):
        try:
            return self.cashback_records.order_by('-created')[0]
        except:
            return None

    @property
    def cash_back_eligible(self):
        if (self.days_since_last_cashback >= self.policy.cash_back_days) and (self.days_since_last_claim >= self.policy.cash_back_days):
            return True
        return False
    cash_back_eligible.fget.short_description = _("Cash back eligibile?")

    def clean(self):
        super(Member, self).clean()
        regex = re.compile(r'^[a-zA-Z\']+$', re.U)
        if not regex.match(self.first_name):
            raise ValidationError({"first_name": 'Invalid name'})

        if not regex.match(self.last_name):
            raise ValidationError({"last_name": 'Invalid name'})

        if self.date_of_birth:
            if self.date_of_birth > datetime.now().date():
                raise ValidationError(_("Date of birth cannot be greater than today's date."))
            else:
                if self.age < 16:
                    raise ValidationError(
                        {'date_of_birth': _("Policy holders can only be 16 years and older.")}
                    )

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Member, self).save(*args, **kwargs)


class Dependant(TimeStampedModel):

    CHILD = "C"
    SPOUSE = "S"
    OTHER = "O"
    RELATIONSHIP_CHOICES = (
        (CHILD, "Child"),
        (SPOUSE, "Spouse"),
        (OTHER, "Other"),
    )
    member = models.ForeignKey(
        Member, on_delete=models.CASCADE, verbose_name=_("Member"),
        related_name="dependants", help_text=_("Reference to policy registrant.")
    )
    relationship = models.CharField(
        verbose_name=_("Relationship"), max_length=1,
        choices=RELATIONSHIP_CHOICES, help_text=_("Relationship to policy registrant.")
    )
    relationship_description = models.TextField(
        verbose_name=_("Relationship description"), null=True, blank=True,
        help_text=_("If relationship is indicated as other, please explain relationship to dependant here.")
    )
    first_name = models.CharField(
        verbose_name=_("First name"), max_length=255,
        help_text=_("Dependant's first name(s).")
    )
    last_name = models.CharField(
        verbose_name=_("Last name"), max_length=255,
        help_text=_("Dependant's last name.")
    )
    date_of_birth = models.DateField(
        verbose_name=_("Date of birth"),
        help_text=_("Dependant's date of birth.")
    )
    sex = models.CharField(
        verbose_name=_("Sex"), max_length=1,
        choices=Member.SEX_CHOICES,
        help_text=_("Dependant's sex orientation.")
    )
    date_joined = models.DateField(
        verbose_name=_("Date joined"),
        help_text=_("Date when dependant was registered.")
    )
    is_deceased = models.BooleanField(
        verbose_name=_("Deceased"), default=False, editable=False,
        help_text=_("Mark dependant as deceased.")
    )

    class Meta:
        verbose_name = _("Dependant")
        verbose_name_plural = _("Dependants")

    def __str__(self):
        return f"{self.full_name}, {self.sex}".title()

    def get_absolute_url(self):
        return reverse('members:view_dependant', kwargs={'pk': self.pk})

    @property
    def full_name(self):
        return f"{self.last_name} {self.first_name}".title()
    full_name.fget.short_description = _("Full name(s)")

    @property
    def age(self):
        today = date.today()
        age = today.year - self.date_of_birth.year - (
            (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
        return age
    age.fget.short_description = _("Age")

    @property
    def relationship_display(self):
        return self.get_relationship_display()
    relationship_display.fget.short_description = _("Relationship")

    @property
    def member_name(self):
        return self.member.full_name
    member_name.fget.short_description = _("Policy holder")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def clean(self):
        regex = re.compile(r'^[a-zA-Z\']+$', re.U)
        if not regex.match(self.first_name):
            raise ValidationError({"first_name": 'Invalid name'})

        if not regex.match(self.last_name):
            raise ValidationError({"last_name": 'Invalid name'})

        if self.date_of_birth:
            if self.date_of_birth > datetime.now().date():
                raise ValidationError(
                    {'date_of_birth': _("Date of birth cannot be greater than today's date.")}
                )

        if self.relationship == "O" and (self.relationship_description is None or self.relationship_description == ""):
            raise ValidationError(
                {'relationship_description': _("Explain the relationship with dependant."), }
            )

        if not self.pk:
            # Validate dependant count
            if self.member.policy is None:
                raise ValidationError(
                    _("%(member)s has not been registered for a policy yet."),
                    params={
                        'member': self.member.full_name,
                    }
                )
            else:

templates/dependant.html
{% extends 'dashboard.html' %}
{% block breadcrump %}
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Home</a></li>
        <li class="breadcrumb-item"><a href="">Dependants</a></li>
        <li class="breadcrumb-item"><a href="">{{ dependant }}</a></li>
    </ul>
{% endblock %}
{% block page_content %}
    <div class="content-box">
        <div class="row">
            <div class="col-sm-12">
                <div class="element-wrapper">
                    <div class="element-box">
                        <div class="row">
                            <div class="col-md-7">
                                <fieldset>
                                    <legend><span>Details</span></legend>
                                </fieldset>
                                <dl>
                                    <dt>Name</dt>
                                    <dd class="lead">{{ dependant.full_name }}</dd>
                                    <dt>Age</dt>
                                    <dd class="lead">{{ dependant.age }}</dd>
                                    <dt>Sex</dt>
                                    <dd class="lead">{{ dependant.get_sex_display }}</dd>
                                    <dt>Date Joined</dt>
                                    <dd class="lead">{{ dependant.date_joined }}</dd>
                                    <dt>Relationship</dt>
                                    <dd class="lead">{{ dependant.get_relationship_display }}</dd>
                                    {% if dependant.relationship == 'O' %}
                                        <dt>Relationship Details</dt>
                                        <dd class="lead">{{ dependant.relationship_description }}</dd>
                                    {% endif %}
                                </dl>
                            </div>
                            <div class="col-md-5">
                                <fieldset>
                                    <legend><span>Actions</span></legend>
                                </fieldset>
                                {% if dependant.is_deceased %}
                                    <a href="javascript:(0)" class="btn btn-outline-danger">
                                        DECEASED
                                    </a>
                                {% else %}
                                    <a href="{% url 'members:edit_dependant' dependant.pk %}"
                                       class="btn btn-outline-warning btn-sm">
                                        <i class="os-icon os-icon-edit-3"></i> Edit Record
                                    </a>
                                    &nbsp;
                                    <a href="" class="btn btn-outline-danger btn-sm float-right">
                                        <i class="os-icon os-icon-database-remove"></i> Remove
                                    </a>
                                    <br>
                                    <br>
                                    <a href="{% url 'members:claim' dependant.pk %}" class="btn btn-outline-primary btn-lg btn-block">
                                        Claim Funeral Cover
                                    </a>
                                {% endif %}
                                <fieldset>
                                    <legend><span>Record Audit</span></legend>
                                </fieldset>
                                <dl>
                                    <dt><small>Added to System</small></dt>
                                    <dd class="text-muted">{{ dependant.created }}</dd>
                                    <dt><small>Last modified</small></dt>
                                    <dd class="text-muted">{{ dependant.modified }}</dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content-panel">
        <div class="content-panel-close"><i class="os-icon os-icon-close"></i></div>
        <div class="element-wrapper"><h6 class="element-header">Dependant(s) on record.</h6>
            <div class="element-box-tp">
                {% for dependant in user.record.dependants.all %}
                    <div class="profile-tile">
                        <div class="profile-tile-box">
                            <div class="pt-avatar-w">
                                {{ dependant.full_name }}
                            </div>
                            <div class="pt-user-name">
                                {{ dependant.get_sex_display }}
                                {% if not dependant.is_deceased %}
                                    , {{ dependant.age }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="profile-tile-meta">
                            <ul>
                                <li>Relationship:<strong>{{ dependant.get_relationship_display }}</strong></li>
                                <li>Added:<strong>{{ dependant.date_joined|date }}</strong></li>
                                {% if dependant.is_deceased %}
                                    <li>Deceased: {{ dependant.claim.date_of_death|date }}</li>
                                {% else %}
                                    <li>Age:<strong>{{ dependant.age }}</strong></li>
                                {% endif %}

                            </ul>
                            <div class="pt-btn">
                                {% if not dependant.is_deceased %}
                                    <a class="btn btn-danger btn-sm" href="#">Remove Dependant</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% empty %}
                    No dependants added yet.
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/dependants.html
{% extends 'dashboard.html' %}
{% block page_title %}
    Dependants List
{% endblock %}
{% block breadcrump %}
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
        <li class="breadcrumb-item"><a href="index-2.html">Products</a></li>
        <li class="breadcrumb-item"><span>Laptop with retina screen</span></li>
    </ul>
{% endblock %}
{% block cpt %}{% endblock %}
{% block page_content %}
    <div class="content-box">
        <div class="element-wrapper">
            <h6 class="element-header">Dependant List</h6>
            <div class="element-box">
                <h5 class="form-header">{{ user.record }}</h5>
                <div class="form-desc">
                    Below is a list of dependants registered under your policy record.
                </div>
                <div class="table-responsive">
                    <table id="tblhhD" width="100%" class="table table-striped table-hover table-lightfont">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Age</th>
                            <th>Sex</th>
                            <th>Relationship</th>
                            <th>Date Joined</th>
                            <th>Deceased?</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Age</th>
                            <th>Sex</th>
                            <th>Relationship</th>
                            <th>Date Joined</th>
                            <th>Deceased?</th>
                            <th>Actions</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for dependant in dependants %}
                            <tr>
                                <td>
                                    <a href="{% url 'members:view_dependant' dependant.pk %}">
                                        {% if dependant.is_deceased %}
                                            <del>
                                                {{ dependant.full_name }}
                                            </del>
                                        {% else %}
                                            {{ dependant.full_name }}
                                        {% endif %}
                                    </a>
                                </td>
                                <td>{{ dependant.age }}</td>
                                <td>{{ dependant.get_sex_display }}</td>
                                <td>{{ dependant.get_relationship_display }}</td>
                                <td>{{ dependant.date_joined }}</td>
                                <td>{{ dependant.is_deceased }}</td>
                                <td>
                                    {% if not dependant.is_deceased %}
                                        <a href="{% url 'members:edit_dependant' dependant.pk %}">
                                            <i class="os-icon os-icon-pencil-2"></i> Edit
                                        </a>
                                        &bull;
                                        <a class="text-danger" href="{% url 'members:delete_dependant' dependant.pk %}">
                                            <i class="os-icon os-icon-database-remove"></i> Remove
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script>
        $("#tblD").dataTable()
    </script>
{% endblock %}

templates/heass.html
{% extends 'dashboard.html' %}
{% block breadcrump %}
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Home</a></li>
        <li class="breadcrumb-item"><a href="">Members</a></li>
        <li class="breadcrumb-item"><span>Health Assessment</span></li>
    </ul>
{% endblock %}
{% block page_title %}
    Health Assessment
{% endblock %}
{% block page_content %}
    <div class="content-box">
        <div class="row">
            <div class="col-sm-12">
                <div class="element-wrapper">
                    <div class="element-box">
                        <form method="post" action="">
                            {% csrf_token %}
                            <h5 class="form-header">Health Assessment (Powered by <a
                                    href="https://www.healthy.co.nz/assessment">healthy.co.nz</a>)</h5>
                            <iframe seamless="seamless" style="width: 100%; height: 470px;" src="https://www.healthy.co.nz/assessment" frameborder="0">

                            </iframe>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head><title>Doves Funeral Services</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="template language" name="keywords">
    <meta content="Tamerlan Soziev" name="author">
    <meta content="Admin dashboard html template" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="favicon.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="http://fast.fonts.net/cssapi/175a63a1-3f26-476a-ab32-4e21cbdb8be2.css" rel="stylesheet" type="text/css">
    <link href="{% static 'bower_components/slick-carousel/slick/slick.css' %}" rel="stylesheet">
    <link href="{% static 'css/front/main8e16.css' %}" rel="stylesheet">
</head>
<body>
<div class="all-wrapper">
    <div class="fade1"></div>
    <div class="desktop-menu menu-top-w menu-activated-on-hover">
        <div class="menu-top-i os-container">
            <!--<div class="logo-w">
                <div class="logo-element"></div>
            </div>-->
            <ul class="main-menu">
                <li class="active"><a href="#sectionIntro">Home</a></li>
            </ul>
            <ul class="small-menu">
                <li class="separate"><a href="{% url 'members:login' %}">Member Login</a></li>
                <li class="separate"><a href="{% url 'members:register' %}">Member Registration</a></li>
                <li><a class="highlight"
                       href="{% url 'instant' %}">Instant Cover</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="intro-w layout-v1" id="sectionIntro">
        <div class="os-container">
            <div class="fade2"></div>
            <div class="intro-i">
                <div class="intro-description">
                    <h1 class="intro-heading">Doves Morgan <span>Funeral</span> Services</h1>
                    
                    <div class="intro-buttons">
                        <a class="btn btn-primary" href="{% url 'members:login' %}" target="_blank">
                            <i class="os-icon os-icon-emoticon-smile"></i>
                            <span>Login</span>
                        </a>
                        <a class="btn btn-link" href="{% url 'instant' %}" target="_blank">
                            <i class="os-icon os-icon-others-43"></i>
                            <span>Instant Cover</span>
                        </a>
                    </div>
                </div>
                <div class="intro-media">
                    <div class="shot shot1">
                        <div class="shot-i" style="background-image: url(%27img/front/intro_chat.html)"></div>
                    </div>
                    <div class="shot shot2">
                        <div class="shot-i" style="background-image: url(%27img/front/intro_profile.html)"></div>
                    </div>
                    <div class="shot shot3">
                        <div class="shot-i" style="background-image: url(%27img/front/intro_dash.html)"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
    <div class="footer-w">
        <div class="fade3"></div>
        <div class="os-container">
            <div class="footer-i">
                <div class="row">
                    <div class="col-sm-7 col-lg-4 b-r padded">
                        <!--<div class="logo-element"></div>-->
                        <h3 class="heading-big">Doves Funeral Services</h3>
                        <h6 class="heading-small">Online Portal</h6>
                       
                    </div>
                    <div class="col-sm-5 col-lg-8">
                        <div class="row">
                            <div class="col-lg-4 b-r padded"><h6 class="heading-small">Locations</h6>
                                <p>157 Harare Street, <br/>Harare, Zimbabwe</p></div>
                            <div class="col-lg-4 b-r padded"><h6 class="heading-small">Phone Numbers</h6>
                                <ul>
                                    <li>0772 765 765</li>
                                    <li>+263 4 244.6272</li>
                                </ul>
                            </div>
                            <div class="col-lg-4 padded"><h6 class="heading-small">Social Links</h6>
                                <ul class="social-links">
                                    <li><a href="https://www.facebook.com/DovesFuneral/"><i class="os-icon os-icon-facebook"></i></a></li>
                                    <li><a href="https://twitter.com/dovesholdingszw?lang=en"><i class="os-icon os-icon-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="deep-footer">Use of this site constitutes acceptance of our <a href="#">User Agreement</a> and
                <a href="#">Privacy Policy</a>. &copy; 2019 Phyllphiry.com All rights reserved.
            </div>
        </div>
    </div>
    <div class="display-type"></div>
</div>
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/slick-carousel/slick/slick.min.js' %}"></script>
<script src="{% static 'bower_components/ion.rangeSlider/js/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<script src="{% static 'bower_components/jquery-bar-rating/dist/jquery.barrating.min.js' %}"></script>
<script src="{% static 'bower_components/moment/moment.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'js/main_frontf5b6.js' %}"></script>
<script>(function (i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
    a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
})(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-42863888-9', 'auto');
ga('send', 'pageview');</script>
</body>
</html>